<a href="https://colab.research.google.com/github/Tinonturja/Model-Evaluation-and-Decision-Tree/blob/master/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello I am excited to start learning pytorch")

hello I am excited to start learning pytorch


In [3]:
print("start our code now")

start our code now


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [5]:
 import torch
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt
 print(torch.__version__)

2.5.1+cu124


#**Introduction to Tensors**

###Creating Tensors

In [6]:
#scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [7]:
scaler.ndim

0

In [8]:
scaler.item()

7

In [9]:
#vector
vector = torch.tensor([7,8])

In [10]:
vector

tensor([7, 8])

In [11]:
 vector2 = torch.tensor([[7,8],[9,10]])
 vector2

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
vector2.ndim

2

In [13]:
#matrix
Matrix = torch.tensor([[7,8],
                       [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
Matrix.ndim

2

In [15]:
Matrix[1]

tensor([ 9, 10])

In [16]:
Matrix[:,1]

tensor([ 8, 10])

In [17]:
 Matrix.shape

torch.Size([2, 2])

In [18]:
#tensors
Tensor = torch.tensor([[1,2,4],
                        [4,5,6],
                        [7,8,9]])
Tensor

tensor([[1, 2, 4],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
Tensor.ndim

2

In [20]:
Tensor[0]

tensor([1, 2, 4])

In [21]:
 Tensor.shape

torch.Size([3, 3])

In [22]:
Tensor2 = torch.tensor([[[1,2],
                         [3,4]],
                        [[4,5],
                         [6,7]]])
Tensor2

tensor([[[1, 2],
         [3, 4]],

        [[4, 5],
         [6, 7]]])

In [23]:
Tensor2.ndim

3

In [24]:
Tensor2.shape

torch.Size([2, 2, 2])

#**Random Tensors**

In [25]:
#first I want to create some random numpy numbers
import numpy as np
import random


In [26]:
a = np.zeros((2,3))
print(a)
b = np.ones((2,3))
print(b)
c = np.random.randint((2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1]


In [27]:
#create a random tensor
random_TENSOR = torch.rand(3,4)
random_TENSOR

tensor([[0.6265, 0.6767, 0.2926, 0.9921],
        [0.8759, 0.5166, 0.1062, 0.7262],
        [0.2758, 0.8720, 0.9398, 0.6008]])

In [28]:
#create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [29]:
#zero and one tensor
rand_tensor = torch.rand(size = (5,10,10))
rand_tensor

tensor([[[4.9264e-01, 3.6795e-02, 1.4693e-01, 1.3062e-01, 7.1102e-01,
          7.2347e-01, 2.3081e-01, 9.1691e-01, 1.3199e-01, 6.4794e-01],
         [1.0286e-01, 2.8214e-01, 2.2136e-01, 2.6550e-01, 3.0921e-01,
          1.0569e-01, 5.9088e-01, 2.1909e-01, 7.6130e-01, 6.5042e-01],
         [5.0617e-01, 6.0402e-01, 7.7174e-01, 5.3706e-01, 2.3929e-01,
          3.4756e-01, 5.4827e-01, 1.9689e-01, 5.6430e-01, 7.9847e-01],
         [3.3819e-01, 2.0697e-01, 9.5717e-01, 8.5924e-01, 4.2103e-01,
          1.4059e-01, 9.1569e-01, 9.2530e-03, 4.1970e-01, 4.9417e-01],
         [6.2203e-01, 6.0030e-01, 2.3841e-01, 6.5192e-01, 8.1356e-01,
          6.5415e-01, 4.2157e-01, 4.9722e-01, 8.2957e-01, 8.6469e-01],
         [3.3687e-01, 1.9235e-01, 1.4026e-01, 8.5553e-01, 8.2611e-01,
          3.1663e-01, 3.7957e-01, 7.0850e-02, 7.7500e-01, 1.0400e-01],
         [1.1378e-01, 1.4963e-02, 4.0203e-01, 9.4204e-01, 9.6407e-01,
          5.6424e-01, 4.2076e-02, 7.3680e-01, 6.1289e-01, 7.5640e-01],
         [4.9

##**Zeros and Ones**

In [30]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##**Creating a range of tensors and tensors like**

In [32]:
#use torch.range()
torch.range(0,10)

<ipython-input-32-d32bca609d4d>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
 #use torch.range()
 one_to_ten = torch.arange(start = 1, end = 1000, step = 73)
 one_to_ten

tensor([  1,  74, 147, 220, 293, 366, 439, 512, 585, 658, 731, 804, 877, 950])

In [35]:
zeros_like = torch.zeros_like(input = one_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
zeros_like.shape

torch.Size([14])

In [37]:
 ones_like = torch.ones_like(input= one_to_ten)
 ones_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

##**Tensor Datatypes**

In [46]:
#float 32 tensor
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                               dtype= None, #what datatype is the tensor
                              device=None, #what device is your tensor on
                              requires_grad=False) #whether or not to track the gradient descent with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

**The main 3 errors one might face while using tensors, they are**


*   Tensors not right datatype
*   Tensors not in right shape
*   Tensors not on the right device



In [44]:
float_32_tensor.dtype

torch.float32

In [47]:
 float_16_tensor = float_32_tensor.type(torch.float16)

In [50]:
#conversion
float_16_tensor
print(float_16_tensor.dtype)

torch.float16


In [54]:
float_64_tensor = torch.tensor([1.,2.,3.],
                               dtype=torch.float64,
                               device = None)
float_64_tensor.dtype


torch.float64

In [55]:
float_64_tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [56]:
float_16_tensors = float_64_tensor.type(torch.float16)
float_16_tensors

tensor([1., 2., 3.], dtype=torch.float16)

In [57]:
#operations in different data types
float_64_tensor + float_16_tensors

tensor([2., 4., 6.], dtype=torch.float64)

In [58]:
#operations in different data types
float_64_tensor * float_16_tensors

tensor([1., 4., 9.], dtype=torch.float64)

In [59]:
#getting information from the tensors
some_tensor = torch.rand(4,5)
some_tensor

tensor([[0.2091, 0.4844, 0.6116, 0.6677, 0.2000],
        [0.3707, 0.5625, 0.3928, 0.3309, 0.4979],
        [0.5158, 0.4781, 0.6676, 0.6673, 0.6635],
        [0.2169, 0.0898, 0.5200, 0.4985, 0.3650]])

In [62]:
#find out details about some tensor
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.device)
print(some_tensor.shape)

tensor([[0.2091, 0.4844, 0.6116, 0.6677, 0.2000],
        [0.3707, 0.5625, 0.3928, 0.3309, 0.4979],
        [0.5158, 0.4781, 0.6676, 0.6673, 0.6635],
        [0.2169, 0.0898, 0.5200, 0.4985, 0.3650]])
torch.float32
cpu
torch.Size([4, 5])


In [65]:
#manipulation tensors(tensor operations)
'''It includes
#addition
#substraction
#multiplication
#matrix multiplication'''

'It includes\n#addition\n#substraction\n#multiplication\n#matrix multiplication'

In [67]:
#create a random torch and add 15
torch = torch.tensor([1,2,3],dtype=torch.int32)
torch + 15

tensor([16, 17, 18], dtype=torch.int32)

In [69]:
#multiply by 15
torch*15

tensor([15, 30, 45], dtype=torch.int32)

In [70]:
torch

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#matrix multiplication