### Imports Library

In [4]:
import numpy as np
import pandas as pd



#for building linear regression problem
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


#for visualization
import matplotlib.pyplot as plt
%matplotlib inline
#for building and training 
import tensorflow as tf

#suppress warning
tf.get_logger().setLevel('ERROR')
tf.autograph.set_verbosity(0)

In [26]:
df = pd.read_csv('/Users/tinonturjamajumder/Downloads/laptop_price - dataset.csv' , encoding = 'latin-1')

In [27]:
df.head()

Company      Product   TypeName  Inches                    ScreenResolution  \
0   Apple  MacBook Pro  Ultrabook    13.3  IPS Panel Retina Display 2560x1600   
1   Apple  Macbook Air  Ultrabook    13.3                            1440x900   
2      HP       250 G6   Notebook    15.6                   Full HD 1920x1080   
3   Apple  MacBook Pro  Ultrabook    15.4  IPS Panel Retina Display 2880x1800   
4   Apple  MacBook Pro  Ultrabook    13.3  IPS Panel Retina Display 2560x1600   

  CPU_Company       CPU_Type  CPU_Frequency (GHz)  RAM (GB)  \
0       Intel        Core i5                  2.3         8   
1       Intel        Core i5                  1.8         8   
2       Intel  Core i5 7200U                  2.5         8   
3       Intel        Core i7                  2.7        16   
4       Intel        Core i5                  3.1         8   

                Memory GPU_Company                GPU_Type  OpSys  \
0            128GB SSD       Intel  Iris Plus Graphics 640  macOS   
1  128GB Flash Storage       Intel        HD Graphics 6000  macOS   
2            256GB SSD       Intel         HD Graphics 620  No OS   
3            512GB SSD         AMD          Radeon Pro 455  macOS   
4            256GB SSD       Intel  Iris Plus Graphics 650  macOS   

   Weight (kg)  Price (Euro)  
0         1.37       1339.69  
1         1.34        898.94  
2         1.86        575.00  
3         1.83       2537.45  
4         1.37       1803.60

In [48]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 765 entries, 57 to 681
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Company              765 non-null    object 
 1   Product              765 non-null    object 
 2   TypeName             765 non-null    object 
 3   Inches               765 non-null    float64
 4   ScreenResolution     765 non-null    object 
 5   CPU_Company          765 non-null    object 
 6   CPU_Type             765 non-null    object 
 7   CPU_Frequency (GHz)  765 non-null    float64
 8   RAM (GB)             765 non-null    int64  
 9   Memory               765 non-null    object 
 10  GPU_Company          765 non-null    object 
 11  GPU_Type             765 non-null    object 
 12  OpSys                765 non-null    object 
 13  Weight (kg)          765 non-null    float64
dtypes: float64(3), int64(1), object(10)
memory usage: 89.6+ KB


In [28]:
df.iloc[3]

Company                                             Apple
Product                                       MacBook Pro
TypeName                                        Ultrabook
Inches                                               15.4
ScreenResolution       IPS Panel Retina Display 2880x1800
CPU_Company                                         Intel
CPU_Type                                          Core i7
CPU_Frequency (GHz)                                   2.7
RAM (GB)                                               16
Memory                                          512GB SSD
GPU_Company                                           AMD
GPU_Type                                   Radeon Pro 455
OpSys                                               macOS
Weight (kg)                                          1.83
Price (Euro)                                      2537.45
Name: 3, dtype: object

In [49]:
df.shape

(1275, 15)

In [50]:
df.columns

Index(['Company', 'Product', 'TypeName', 'Inches', 'ScreenResolution',
       'CPU_Company', 'CPU_Type', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Memory',
       'GPU_Company', 'GPU_Type', 'OpSys', 'Weight (kg)', 'Price (Euro)'],
      dtype='object')

In [51]:
X=df.drop(columns=['Price (Euro)'])

In [52]:
X.shape

(1275, 14)

In [53]:
y=df['Price (Euro)']

In [54]:
y.shape

(1275,)

In [55]:
y.head()

0    1339.69
1     898.94
2     575.00
3    2537.45
4    1803.60
Name: Price (Euro), dtype: float64

In [56]:
y.ndim

1

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=10 , test_size=0.2)

In [22]:
X_train.shape

(604, 17)

In [57]:
X_train.describe()


Inches  CPU_Frequency (GHz)    RAM (GB)  Weight (kg)
count  765.000000           765.000000  765.000000   765.000000
mean    15.100523             2.319712    8.630065     2.076233
std      1.398700             0.490506    5.500632     0.687867
min     10.100000             0.900000    2.000000     0.690000
25%     14.000000             2.000000    4.000000     1.580000
50%     15.600000             2.500000    8.000000     2.090000
75%     15.600000             2.700000    8.000000     2.330000
max     17.300000             3.600000   64.000000     4.700000

In [24]:
X_train.describe().round(3)

id    season  dl_applied  win_by_runs  win_by_wickets
count    604.000   604.000     604.000      604.000         604.000
mean    1935.929  2013.558       0.028       12.629           3.439
std     3584.117     3.418       0.166       22.146           3.397
min        1.000  2008.000       0.000        0.000           0.000
25%      186.750  2011.000       0.000        0.000           0.000
50%      388.000  2013.000       0.000        0.000           4.000
75%      577.250  2017.000       0.000       18.000           6.000
max    11415.000  2019.000       1.000      140.000          10.000

In [38]:
#divide into train, validation and test dataset
#first divide into train and other sector
X_train, x_, y_train , y_ = train_test_split(X, y, random_state=16, test_size=0.4)

#split the remaining 40 percent into validation and test file

x_cv, x_test, y_cv , y_test = train_test_split(x_, y_, test_size=0.50, random_state=16)

#delete temporary variables

del x_, y_

print(f"the shape of the training set (input) is: {X_train.shape}")
print(f"the shape of the training set (target) is: {y_train.shape}\n")
print(f"the shape of the cross validation set (input) is: {x_cv.shape}")
print(f"the shape of the cross validation set (target) is: {y_cv.shape}\n")
print(f"the shape of the test set (input) is: {x_test.shape}")
print(f"the shape of the test set (target) is: {y_test.shape}")


the shape of the training set (input) is: (765, 14)
the shape of the training set (target) is: (765,)

the shape of the cross validation set (input) is: (255, 14)
the shape of the cross validation set (target) is: (255,)

the shape of the test set (input) is: (255, 14)
the shape of the test set (target) is: (255,)


In [17]:
y_train=np.expand_dims(y_train, axis=1)
y_cv=np.expand_dims(y_cv, axis=1)
y_test=np.expand_dims(y_test, axis=1)

In [58]:
y_cv.shape
y_test.shape

(255,)

In [59]:
y_train.head

<bound method NDFrame.head of 57       586.19
831     2099.00
419     1215.38
312     2099.00
679     1299.00
         ...   
635      906.62
581     1008.52
121     2241.50
1262     459.00
681      419.00
Name: Price (Euro), Length: 765, dtype: float64>

#### Feature Scaling

It's a good idea to perform feature scaling to help your model to converge faster. this is especially true if your input features have widely different range of values.

In [60]:
X_train.describe().round(3)


Inches  CPU_Frequency (GHz)  RAM (GB)  Weight (kg)
count  765.000              765.000   765.000      765.000
mean    15.101                2.320     8.630        2.076
std      1.399                0.491     5.501        0.688
min     10.100                0.900     2.000        0.690
25%     14.000                2.000     4.000        1.580
50%     15.600                2.500     8.000        2.090
75%     15.600                2.700     8.000        2.330
max     17.300                3.600    64.000        4.700

In [68]:
numeric_features = X_train.select_dtypes(include=['number']).columns

print(numeric_features)


Index(['Inches', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Weight (kg)'], dtype='object')


In [70]:
X_train_numeric = X_train[numeric_features]
print(X_train_numeric.columns)

Index(['Inches', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Weight (kg)'], dtype='object')


In [74]:
scaler= StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_numeric)

print(f"Computed mean of the training set: {scaler.mean_}")
print(f"Computed standard deviation of the training set: {scaler.scale_}")


Computed mean of the training set: [15.10052288  2.31971242  8.63006536  2.07623268]
Computed standard deviation of the training set: [1.39778527 0.49018542 5.49703527 0.68741758]


In [91]:
print(X_train_scaled)

[[ 0.35733466  0.36779466 -0.84228409 -0.11089719]
 [-0.78733329  0.5717991   1.34071082 -1.42014507]
 [-0.78733329 -1.06023638 -0.11461912 -0.47457716]
 ...
 [ 0.35733466  0.97980797  1.34071082 -0.40184117]
 [ 0.35733466  0.16379023 -0.47845161  0.32551876]
 [ 0.35733466 -2.48826743 -0.84228409 -0.31455797]]


In [79]:
#initialize the class
linear_model = LinearRegression()

#train the model
linear_model.fit(X_train_scaled, y_train)

LinearRegression()

In [88]:
#feed the scaled training set and get the predictions
yhat = linear_model.predict(X_train_scaled)

#use scikit-learn's utility function and divide by 2
print(f"training MSE (using sklearn function): {mean_squared_error(y_train, yhat)/2}")

#for-loop implementation
total_squared_error = 0

for i in range(len(yhat)):
    squared_error_i = (yhat[i] - y_train[i])**2
    total_squared_error += squared_error_i
mse = total_squared_error / (2*len(yhat))

print(f"training MSE (for-loop implementation): {mse}")


training MSE (using sklearn function): 103489.68394597336
training MSE (for-loop implementation): 103489.68394597348


In [92]:
#in summary what I had done till the date is
#import model and necessary functions
import numpy as np
import pandas as pd

#import scikitlearn functions
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import mean_squared_error

#import data set 

#visualize the dataset

#split the dataset into test, train and validation segments

#standardize the dataset

#fit the dataset into linear model

#predict the value of the dataset

#calculate total error
 

In [110]:
#first collect the numeric features of x_cv
numeric_features = x_cv.select_dtypes(include=['number']).columns
x_cv_scaled = x_cv[numeric_features]

In [96]:
#scale the cv set using the mean and std of the training dataset
x_cv_scaled = scaler.transform(x_cv_scaled)

print(f"Mean used to scale the CV set: {scaler.mean_}")
print(f"standard deviation used to scale the CV set: {scaler.scale_}")


#feed the scaled cross validation set

yhat = linear_model.predict(x_cv_scaled)

#use scikit-learn's utility function and divide by 2
print(f"Cross validation MSE: {mean_squared_error(y_cv, yhat)/2}")

Mean used to scale the CV set: [15.10052288  2.31971242  8.63006536  2.07623268]
standard deviation used to scale the CV set: [1.39778527 0.49018542 5.49703527 0.68741758]
Cross validation MSE: 81496.14500961034


##### Adding Polynomial Features


In [98]:
#create additional features
poly = PolynomialFeatures(degree=2, include_bias=False)
#compute the number of features and transform the training set
X_train_mapped = poly.fit_transform(X_train_scaled)

# Preview the first 5 elements of the new training set. Left column is `x` and right column is `x^2`
# Note: The `e+<number>` in the output denotes how many places the decimal point should 
# be moved. For example, `3.24e+03` is equal to `3240`

print(X_train_mapped[:5])

[[ 0.35733466  0.36779466 -0.84228409 -0.11089719  0.12768806  0.13142578
  -0.3009773  -0.03962741  0.13527291 -0.30978759 -0.0407874   0.70944249
   0.09340694  0.01229819]
 [-0.78733329  0.5717991   1.34071082 -1.42014507  0.61989371 -0.45019647
  -1.05558626  1.11812749  0.32695421  0.76661724 -0.81203767  1.79750549
  -1.90400385  2.01681201]
 [-0.78733329 -1.06023638 -0.11461912 -0.47457716  0.61989371  0.8347594
   0.09024345  0.3736504   1.12410119  0.12152336  0.50316397  0.01313754
   0.05439562  0.22522348]
 [ 0.35733466  0.97980797  1.34071082  1.0528787   0.12768806  0.35011935
   0.47908245  0.37623005  0.96002365  1.31363914  1.03161893  1.79750549
   1.41160585  1.10855355]
 [ 0.35733466  0.36779466  1.34071082  0.61646274  0.12768806  0.13142578
   0.47908245  0.2202835   0.13527291  0.49310628  0.2267317   1.79750549
   0.82649826  0.38002631]]


In [99]:
#instance the class
scaler_poly = StandardScaler()

#Compute the mean and standard deviation of the training set then transform it
X_train_mapped_scaled = scaler_poly.fit_transform(X_train_mapped)

#preview the first 5 elements of the scaled training set
print(X_train_mapped_scaled[:5])


[[ 0.35733466  0.36779466 -0.84228409 -0.11089719 -0.65055823 -0.13164387
  -0.43261309 -0.70867415 -0.62783454 -0.69341118 -0.3701212  -0.0656375
  -0.15762578 -0.46457688]
 [-0.78733329  0.5717991   1.34071082 -1.42014507 -0.28347803 -0.63226879
  -1.03606008  0.2425162  -0.48866446  0.4522459  -1.1515325   0.18015802
  -1.14423809  0.47826919]
 [-0.78733329 -1.06023638 -0.11461912 -0.47457716 -0.28347803  0.47374278
  -0.11976101 -0.36913263  0.09010359 -0.23435113  0.18099658 -0.22293412
  -0.17689525 -0.36442502]
 [ 0.35733466  0.97980797  1.34071082  1.0528787  -0.65055823  0.0565942
   0.19118642 -0.36701323 -0.0290248   1.03446135  0.71641381  0.18015802
   0.4934928   0.05105941]
 [ 0.35733466  0.36779466  1.34071082  0.61646274 -0.65055823 -0.13164387
   0.19118642 -0.49513607 -0.62783454  0.16113818 -0.09907761  0.18015802
   0.20448147 -0.29161174]]


In [100]:
#initialize the class
model  = LinearRegression()

#train the model
model.fit(X_train_mapped_scaled, y_train)

#compute the training MSE
yhat = model.predict(X_train_mapped_scaled)
print(f"Training MSE: {mean_squared_error(y_train , yhat)/2}")

#add the polynomial features to the cross validation set
x_cv_mapped= poly.transform(x_cv_scaled)

#scale the cross validation set using the mean and std of training set
x_cv_mapped_scaled = scaler_poly.transform(x_cv_mapped)

#compute the corss validation MSE
yhat = model.predict(x_cv_mapped_scaled)
print(f"Cross validation MSE: {mean_squared_error(y_cv, yhat) / 2}")


Training MSE: 82298.38775490818
Cross validation MSE: 80615.93951003108


##### Continuously adding degrees

In [105]:
#initialize list to save the errors, models, and feature transforms
train_mses = []
cv_mses = []
polys = []
scalers = []
models=[]


#loop over 10 times. Each adding one more degree of polynomial higher than the last

for degree in range(1,11):
    #add polynomial features to the training set
    poly = PolynomialFeatures(degree, include_bias= False)
    X_train_mapped = poly.fit_transform(X_train_numeric)
    polys.append(poly)


    #scale the training set
    scaler_poly = StandardScaler()
    X_train_mapped_scaled = scaler_poly.fit_transform(X_train_mapped)
    scalers.append(scaler_poly)


    #create and train the model
    model = LinearRegression()
    model.fit(X_train_mapped_scaled, y_train)
    models.append(model)

    #compute the training MSE
    yhat = model.predict (X_train_mapped_scaled)
    train_mse = mean_squared_error(y_train, yhat)/2
    train_mses.append(train_mse)


    # Add polynomial features and scale the cross validation set
    X_cv_mapped = poly.transform(x_cv_scaled)
    X_cv_mapped_scaled = scaler_poly.transform(X_cv_mapped)
    
    # Compute the cross validation MSE
    yhat = model.predict(X_cv_mapped_scaled)
    cv_mse = mean_squared_error(y_cv, yhat) / 2
    cv_mses.append(cv_mse)

    print(f" degree: {degree} --> Train_MSE: {train_mses} --> CV_MSES: {cv_mse}")

/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with f

 degree: 1 --> Train_MSE: [103489.68394597336] --> CV_MSES: 153475.98972253373
 degree: 2 --> Train_MSE: [103489.68394597336, 82298.38775490818] --> CV_MSES: 4866728.1381051885
 degree: 3 --> Train_MSE: [103489.68394597336, 82298.38775490818, 66195.25750195887] --> CV_MSES: 207839701.83168235
 degree: 4 --> Train_MSE: [103489.68394597336, 82298.38775490818, 66195.25750195887, 56850.300350820005] --> CV_MSES: 17318244384.336956
 degree: 5 --> Train_MSE: [103489.68394597336, 82298.38775490818, 66195.25750195887, 56850.300350820005, 45057.31192438235] --> CV_MSES: 7524455534286.294
 degree: 6 --> Train_MSE: [103489.68394597336, 82298.38775490818, 66195.25750195887, 56850.300350820005, 45057.31192438235, 36446.698370262166] --> CV_MSES: 3.9682476707705555e+17
 degree: 7 --> Train_MSE: [103489.68394597336, 82298.38775490818, 66195.25750195887, 56850.300350820005, 45057.31192438235, 36446.698370262166, 28557.53415989372] --> CV_MSES: 7.576147913854148e+23


/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


 degree: 8 --> Train_MSE: [103489.68394597336, 82298.38775490818, 66195.25750195887, 56850.300350820005, 45057.31192438235, 36446.698370262166, 28557.53415989372, 21580.431629510764] --> CV_MSES: 5.09967172409131e+23


/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


 degree: 9 --> Train_MSE: [103489.68394597336, 82298.38775490818, 66195.25750195887, 56850.300350820005, 45057.31192438235, 36446.698370262166, 28557.53415989372, 21580.431629510764, 17279.559819740603] --> CV_MSES: 9.531633969558555e+26
 degree: 10 --> Train_MSE: [103489.68394597336, 82298.38775490818, 66195.25750195887, 56850.300350820005, 45057.31192438235, 36446.698370262166, 28557.53415989372, 21580.431629510764, 17279.559819740603, 17095.88688342306] --> CV_MSES: 6.234404215046042e+28


/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


In [109]:
#initialize lists
train_mses = []
cv_mses = []

for degree in range(1, 11):
    # Polynomial features
    poly = PolynomialFeatures(degree, include_bias=False)
    X_train_poly = poly.fit_transform(X_train_numeric)
    X_cv_poly = poly.transform(x_cv_scaled)

    # Scaling
    scaler = StandardScaler()
    X_train_poly_scaled = scaler.fit_transform(X_train_poly)
    X_cv_poly_scaled = scaler.transform(X_cv_poly)

    # Model with regularization
    model = Ridge(alpha=0.1)  # Ridge or Lasso to control overfitting
    model.fit(X_train_poly_scaled, y_train)

    # Compute MSEs
    train_mse = mean_squared_error(y_train, model.predict(X_train_poly_scaled)) / 2
    cv_mse = mean_squared_error(y_cv, model.predict(X_cv_poly_scaled)) / 2

    train_mses.append(train_mse)
    cv_mses.append(cv_mse)

    print(f"Degree: {degree}, Train_MSE: {train_mse:.4f}, CV_MSE: {cv_mse:.4f}")


/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(
/Users/tinonturjamajumder/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with f

Degree: 1, Train_MSE: 103489.6870, CV_MSE: 153377.4874
Degree: 2, Train_MSE: 82470.6982, CV_MSE: 3860835.5006
Degree: 3, Train_MSE: 70627.7452, CV_MSE: 1387404.9187
Degree: 4, Train_MSE: 67690.3099, CV_MSE: 10183912.9305
Degree: 5, Train_MSE: 65788.7869, CV_MSE: 19142232.1333
Degree: 6, Train_MSE: 63984.3461, CV_MSE: 19637395.0718
Degree: 7, Train_MSE: 62071.0610, CV_MSE: 12266836.9000
Degree: 8, Train_MSE: 60087.5137, CV_MSE: 7049115.1053
Degree: 9, Train_MSE: 58307.2902, CV_MSE: 3903888.4297
Degree: 10, Train_MSE: 56837.6384, CV_MSE: 2442486.3914


In [108]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=1.0)  # Adjust alpha for regularization strength
